# This file lists all configuration options with their default values.
# You do not need to duplicate all the values in your own user or project config.
# Only override what is needed.

[core]
# Use incremental resolution of project-wide references.
# This is much more efficient but is currently experimental
incremental_references = true

[completion]
# The style of wiki links completion.
# Values include:
# - "title-slug" to complete using the document title.
# - "file-stem" to complete using file name without an extension.
# - "file-path-stem" same as above but using file path.
wiki.style = "file-stem"
