{ pkgs, home-manager, specialArgs, userName, ... }: # nixos-wsl

{  
  imports = [ 
    home-manager.nixosModules.home-manager 
  ];

  #users.mutableUsers = true;

  # define a user account, don't forget to set a password with ‘passwd’
  users.users."${userName}" = {
    # the hashed password with salt is generated by run `mkpasswd`.
    hashedPassword = "$6$11niI8PHfcNgMejh$0NdIXjJ0zvRLyLpoZvViN3KvLAGZ3.VlZYlDVPo8hX9CV./Etphn335g8m7uaR/J1OpOYaLsfL5.rYDlwCa6h/";
    home = "/home/${userName}";
    isNormalUser = true;
    # use fish as default interactive shell while maintaining bash compatibility for scripts
    shell = pkgs.fish;
    extraGroups = [
      userName
      "users"
      "wheel"
      "docker"
      "adbusers"
    ];
    openssh.authorizedKeys.keys = []; #TODO: add your public key here
  };

  #TODO: add conditional to enable this only on WSL
  wsl = {
    defaultUser = userName;
  };

  home-manager = {
    useGlobalPkgs = true;
    useUserPackages = true;
    users."${userName}" = import ../home; # TODO: consider passing either self or root
    extraSpecialArgs = specialArgs; # specialArgs // {hostname = config.networking.hostName;};
    #extraSpecialArgs = lib.removeAttrs specialArgs [ "lib" ];      
    #sharedModules = [ inputs.sops-nix.homeManagerModules.sops ];
  };
  
  # https://github.com/jonaswouters/nixos-configuration/blob/master/users.nix
  #home-manager.users.${userName} = {
  #  programs.ssh = {
  #    enable = true;
  #    forwardAgent = true;
  #  };
  #  
  #  services.gpg-agent = {
  #    enable = true;
  #    enableSshSupport = true;
  #  };
  #};

  # turn off password prompt when using sudo
  security.sudo.extraRules = [
    {
      users = [userName];
      commands = [
        {
          command = "ALL";
          options = ["NOPASSWD"];
        }
      ];
    }
  ];

  # set as trusted users for using mirrors (all users can add Nix caches)
  nix.settings.trusted-users = [ userName ]; 
}