keys:
  - users:
    - &paz age1deutem40xwzf47lh9uqzax69htywpyfwgy5wh8yl2n7rl3j24ajquusyvh
  - hosts:
    - &crodax age1zx6jdyrqz6safghgddh6e6hku2wmcxuf6d2vp5fw7kzhvt3hu5rs2thakh
    - &crobex age1tgkt3lw0enhr5lt82d3uhtsa8gwpkc66eecj2chrj8jp3z2zlf7st84jv7
creation_rules:
  - path_regex: .(yaml|json|env|ini)$
    key_groups:
    - age:
      - *paz
      - *crodax
      - *crobex
