{ userName, ... }:

{
  # set as trusted users for using mirrors
  nix.settings.trusted-users = [ userName ];

  # define a user account. Don't forget to set a password with ‘passwd’.
  users.users."${userName}" = {
    # the hashed password with salt is generated by run `mkpasswd`.
    hashedPassword = "$6$11niI8PHfcNgMejh$0NdIXjJ0zvRLyLpoZvViN3KvLAGZ3.VlZYlDVPo8hX9CV./Etphn335g8m7uaR/J1OpOYaLsfL5.rYDlwCa6h/";
    home = "/home/${userName}";
    isNormalUser = true;
    extraGroups = [
      userName
      "users"
      "wheel"
      "docker"
      "adbusers"
    ];
    openssh.authorizedKeys.keys = []; # TODO: add your public key here
  };

  # Turn off password prompt when using sudo.
  security.sudo.extraRules = [
    {
      users = [userName];
      commands = [
        {
          command = "ALL";
          options = ["NOPASSWD"];
        }
      ];
    }
  ];
}